### ISSUE TITLE
Would you please provide a compiled kext?

### ISSUE THREAD

**Issue by inspiredearth** [TomHeaven/HoRNDIS#2]
Thanks very much for providing this M1 compatible (and macOS 12+ compatible) project for HoRNDIS.

I have a mac M1 with 256GB SSD. Installing 12+ GB of XCODE on there is something I'd rather avoid.

Would you be willing to provide a compiled and signed kext file? 

Based on what I'm seeing online, there would be a lot of users who would benefit from it. People like me (who have the know-how to compile projects, etc., but don't wish to install XCODE if that's all they are going to use if for) and also those who simply don't have the skills required.

**Comment by TomHeaven** [comment]
I've compiled the kext signed with my personal developer ID. Please try it: https://github.com/TomHeaven/HoRNDIS/releases/tag/rel9.3_2.
